### ISSUE TITLE
予約件数が多い場合に予約一覧をスクロール表示にする

### ISSUE THREAD

**Issue by n-matsumoto-cl** [n-matsumoto-cl/meeting-room-reservation-system#1]
## 概要

現在、会議室予約情報（予約一覧）は全件がそのまま表示されており、予約件数が多くなると画面が縦に長くなり操作性が低下します。

## 要望

- 予約件数が多くなった場合でも、予約一覧部分のみをスクロール可能なエリア（高さ制限＋overflow: auto等）に変更し、UI/UXを向上させてください。
- スクロールバーのデザインもモダンなものにしてください。
- 予約一覧の最大表示高さはデザインに合わせて適切に設定してください。

## 関連箇所
- `index.html`（予約一覧表示部分）
- `styles.css`（予約一覧の高さ・スクロール設定）

## 参考実装例
```css
.reservation-list {
  max-height: 400px;
  overflow-y: auto;
  /* スクロールバーのカスタマイズも推奨 */
}
```

## 備考
- 既存の予約一覧表示機能との整合性に注意してください。
- モバイル表示時の挙動も考慮してください。
